rules:
  indent:
    - 2
    - 4
  quotes:
    - 0
  linebreak-style:
    - 2
    - unix
  semi:
    - 2
    - always
  prefer-const:
    - 2
env:
  node: true
  es6: true
  mocha: true
extends: 'eslint:recommended'
